searchDeep = 8
countLimit = 20   # board.generator() 
star = True       # board.generator()
timeLimit = 5 # sec
cache = False
spreadLimit = 1
opening = True
starSpread = False
vcxDeep = 5
debug = False
log = False
eval_point = False
clear_cache = False # negamax.deeping()
gen = False
random = False