searchDeep = 8
countLimit = 20   # board.generator() 
star = True       # board.generator()
timeLimit = 3 # sec
cache = False
spreadLimit = 1
opening = True
starSpread = True
vcxDeep = 5
debug = True
log = True
eval_point = False
clear_cache = False # negamax.deeping()
gen = False
random = True