searchDeep = 8
countLimit = 20   # board.generator() 
star = True       # board.generator()
timeLimit = 7 # sec
cache = True
spreadLimit = 1
opening = True
starSpread = True
vcxDeep = 5
debug = False
log = True
eval_point = False
clear_cache = False # negamax.deeping()
onlyThrees = False